[package]
name = "pane-resizer"
version = "0.1.2"
edition = "2021"
description = "A simple pane resizer for Leptos"
license = "MIT"
readme = "../README.md"
repository = "https://github.com/jonsaw/pane-resizer"

[dependencies]
leptos = { version = "0.7" }
leptos-use = { version = "0.15" }
